"""Add comments_enabled field to blog_posts

Revision ID: 181d92eb2f3b
Revises: b120f4eee6be
Create Date: 2025-09-26 23:17:59.664283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "181d92eb2f3b"
down_revision: Union[str, Sequence[str], None] = "b120f4eee6be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable with default value
    op.add_column(
        "blog_posts",
        sa.Column(
            "comments_enabled", sa.Boolean(), nullable=True, server_default="true"
        ),
    )

    # Update existing rows to have the default value
    op.execute(
        "UPDATE blog_posts SET comments_enabled = true WHERE comments_enabled IS NULL"
    )

    # Now make the column NOT NULL
    op.alter_column(
        "blog_posts", "comments_enabled", nullable=False, server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_posts", "comments_enabled")
    # ### end Alembic commands ###
