"""Add image support and refactor to generic Tag/Category models

Revision ID: 40124169be94
Revises: 6dddf926ebb1
Create Date: 2025-09-28 20:54:24.604300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "40124169be94"
down_revision: Union[str, Sequence[str], None] = "6dddf926ebb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tags_content_type"), "tags", ["content_type"], unique=False
    )
    op.create_index(op.f("ix_tags_id"), "tags", ["id"], unique=False)
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_index(op.f("ix_tags_slug"), "tags", ["slug"], unique=True)

    # First drop the foreign key constraint
    op.drop_constraint(
        op.f("blog_post_tags_tag_id_fkey"), "blog_post_tags", type_="foreignkey"
    )

    # Then drop the old blog_tags table
    op.drop_index(op.f("ix_blog_tags_id"), table_name="blog_tags")
    op.drop_index(op.f("ix_blog_tags_name"), table_name="blog_tags")
    op.drop_index(op.f("ix_blog_tags_slug"), table_name="blog_tags")
    op.drop_table("blog_tags")

    # Finally create the new foreign key constraint
    op.create_foreign_key(None, "blog_post_tags", "tags", ["tag_id"], ["id"])
    op.add_column(
        "blog_posts",
        sa.Column("background_image_url", sa.String(length=500), nullable=True),
    )
    op.create_foreign_key(None, "blog_posts", "users", ["author_id"], ["id"])
    op.add_column(
        "categories", sa.Column("image_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "categories", sa.Column("content_type", sa.String(length=50), nullable=True)
    )
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=False)
    op.create_index(
        op.f("ix_categories_content_type"), "categories", ["content_type"], unique=False
    )
    op.drop_column("categories", "icon")
    op.drop_column("categories", "color")
    op.drop_column("categories", "path")
    op.create_foreign_key(None, "comments", "users", ["author_id"], ["id"])
    op.create_foreign_key(None, "email_verifications", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "user_comment_likes", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "user_follows", "users", ["following_id"], ["id"])
    op.create_foreign_key(None, "user_follows", "users", ["follower_id"], ["id"])
    op.create_foreign_key(None, "user_post_favorites", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "user_post_likes", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_post_likes", type_="foreignkey")
    op.drop_constraint(None, "user_post_favorites", type_="foreignkey")
    op.drop_constraint(None, "user_follows", type_="foreignkey")
    op.drop_constraint(None, "user_follows", type_="foreignkey")
    op.drop_constraint(None, "user_comment_likes", type_="foreignkey")
    op.drop_constraint(None, "email_verifications", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.add_column(
        "categories",
        sa.Column("path", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.add_column(
        "categories",
        sa.Column("color", sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    )
    op.add_column(
        "categories",
        sa.Column("icon", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_categories_content_type"), table_name="categories")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.drop_column("categories", "content_type")
    op.drop_column("categories", "image_url")
    op.drop_constraint(None, "blog_posts", type_="foreignkey")
    op.drop_column("blog_posts", "background_image_url")
    op.drop_constraint(None, "blog_post_tags", type_="foreignkey")
    op.create_foreign_key(
        op.f("blog_post_tags_tag_id_fkey"),
        "blog_post_tags",
        "blog_tags",
        ["tag_id"],
        ["id"],
    )
    op.create_table(
        "blog_tags",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("color", sa.VARCHAR(length=7), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("blog_tags_pkey")),
    )
    op.create_index(op.f("ix_blog_tags_slug"), "blog_tags", ["slug"], unique=True)
    op.create_index(op.f("ix_blog_tags_name"), "blog_tags", ["name"], unique=True)
    op.create_index(op.f("ix_blog_tags_id"), "blog_tags", ["id"], unique=False)
    op.drop_index(op.f("ix_tags_slug"), table_name="tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_index(op.f("ix_tags_id"), table_name="tags")
    op.drop_index(op.f("ix_tags_content_type"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
