"""add_is_email_verified_field_to_users

Revision ID: 6dddf926ebb1
Revises: 46a6a4500483
Create Date: 2025-09-28 16:07:47.257023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6dddf926ebb1"
down_revision: Union[str, Sequence[str], None] = "46a6a4500483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable
    op.add_column("users", sa.Column("is_email_verified", sa.Boolean(), nullable=True))

    # Step 2: Update existing records to set default value
    op.execute(
        "UPDATE users SET is_email_verified = false WHERE is_email_verified IS NULL"
    )

    # Step 3: Make column non-nullable
    op.alter_column("users", "is_email_verified", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_email_verified")
    # ### end Alembic commands ###
