"""Add image library table

Revision ID: eadcbae9d9e0
Revises: be1a13480ed4
Create Date: 2025-09-29 13:31:32.803085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eadcbae9d9e0'
down_revision: Union[str, Sequence[str], None] = 'be1a13480ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='存储的文件名'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件存储路径'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='文件访问URL'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME类型'),
    sa.Column('width', sa.Integer(), nullable=True, comment='图片宽度'),
    sa.Column('height', sa.Integer(), nullable=True, comment='图片高度'),
    sa.Column('description', sa.Text(), nullable=True, comment='图片描述'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签(逗号分隔)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='上传用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_library_id'), 'image_library', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_library_id'), table_name='image_library')
    op.drop_table('image_library')
    # ### end Alembic commands ###
